package com.solo.backend.mapper;

import com.solo.backend.dto.ReservationDTO;
import com.solo.backend.model.Reservation;
import com.solo.backend.model.User;
import com.solo.backend.model.Hotel;

public class ReservationMapper {

    public static Reservation toEntity(ReservationDTO dto, User user, Hotel hotel) {
        // Assuming 'id' will be generated by the database
        return new Reservation(
            null,               // 'id' can be null if auto-generated
            user,                  // Map User object
            hotel,                 // Map Hotel object
            dto.getCheckInDate(),  // Map checkInDate
            dto.getCheckOutDate(), // Map checkOutDate
            dto.getStatus()        // Map status
        );
    }
}
